--DROP TABLE DM_CATEGORIAS_DESTINO

CREATE TABLE DM_CATEGORIAS_DESTINO (
    ID_CATEGORIA INTEGER PRIMARY KEY NOT NULL,
    CATEGORIA TEXT NOT NULL,
    ID_TIPO INTEGER NOT NULL,
    LAST_UPDATE TIMESTAMP NOT NULL
);
