--DROP TABLE DM_TIPOS_PACOTES

CREATE TABLE DM_TIPOS_PACOTES (
    ID_TIPO INTEGER NOT NULL,
    TIPO TEXT NOT NULL,
    ID_PACOTE INTEGER NOT NULL,
    LAST_UPDATE TIMESTAMP NOT NULL,
    PRIMARY KEY (ID_TIPO, ID_PACOTE)
);
