-- TABELA DE USUARIO
---
--AUOTOR: OCATVIO
-----
--DROP TABLE USUARIO

CREATE TABLE DM_USUARIO (
    ID_USUARIO INTEGER PRIMARY KEY AUTOINCREMENT,
    CPF VARCHAR(20) NOT NULL,
    NOME TEXT NOT NULL,
    ID_PACOTE INTEGER,
    LAST_UPDATE TIMESTAMP NOT NULL
);
