--DROP TABLE DM_USUARIOS

CREATE TABLE DM_USUARIOS (
    ID_USUARIO INTEGER PRIMARY KEY AUTOINCREMENT,
    CPF VARCHAR(20) NOT NULL,
    NOME TEXT NOT NULL,
    ID_PACOTE INTEGER,
    LAST_UPDATE TIMESTAMP NOT NULL,
    FOREIGN KEY (ID_PACOTE) REFERENCES DM_PACOTES(ID_PACOTE)
);
