CREATE TABLE DM_USUARIOS (
    ID_USUARIO  INTEGER      PRIMARY KEY AUTOINCREMENT,
    CPF         VARCHAR (20) NOT NULL,
    NOME        TEXT         NOT NULL,
    EMAIL       TEXT         NOT NULL,
    SENHA       TEXT         NOT NULL,
    LAST_UPDATE TIMESTAMP    NOT NULL
);