CREATE TABLE FT_VIAGENS (
    ID_USUARIO   INTEGER,
    ID_PACOTE    INTEGER,
    DATA_RESERVA VARCHAR (20),
    FOREIGN KEY (
        ID_USUARIO
    )
    REFERENCES DM_USUARIOS (ID_USUARIO),
    FOREIGN KEY (
        ID_PACOTE
    )
    REFERENCES DM_PACOTE_VIAGEM (id) 
);
