--DROP TABLE FT_VIAGENS

CREATE TABLE FT_VIAGENS (
    ID_USUARIO INTEGER,
    ID_PACOTE INTEGER,
    ID_TIPO INTEGER,
    ID_CATEGORIA INTEGER,
    NOME TEXT,
    CPF VARCHAR(20),
    PACOTE TEXT,
    TIPO TEXT,
    CATEGORIA TEXT,
    DATA_RESERVA TIMESTAMP,
    DATA_CARGA TIMESTAMP);
