INSERT INTO DM_CATEGORIAS_DESTINO (ID_CATEGORIA, CATEGORIA, ID_TIPO, LAST_UPDATE)
VALUES 
(1, "MONTANHA", 1, CURRENT_TIMESTAMP),
(2, "DESERTO", 1, CURRENT_TIMESTAMP),
(3, "PRAIA", 2, CURRENT_TIMESTAMP),
(4, "TROPICAL", 2, CURRENT_TIMESTAMP),
(5, "METROPOLE", 3, CURRENT_TIMESTAMP);

