INSERT INTO DM_TIPOS_PACOTES (ID_TIPO, TIPO, ID_PACOTE, LAST_UPDATE)
VALUES 
(1, 'AVENTURA', 1, CURRENT_TIMESTAMP),
(2, 'RELAXAMENTO', 1, CURRENT_TIMESTAMP),
(3, 'CULTURA', 1, CURRENT_TIMESTAMP),
(2, 'RELAXAMENTO', 2, CURRENT_TIMESTAMP),
(3, 'CULTURA', 2, CURRENT_TIMESTAMP),
(3, 'CULTURA', 3, CURRENT_TIMESTAMP);

