INSERT INTO FT_VIAGENS(
    ID_USUARIO,
    ID_PACOTE,
    ID_TIPO,
    ID_CATEGORIA,
    NOME,
    CPF,
    PACOTE,
    TIPO,
    CATEGORIA,
    DATA_RESERVA,
    DATA_CARGA)
SELECT
USU.ID_USUARIO,
PC.ID_PACOTE,
TP.ID_TIPO,
CD.ID_CATEGORIA,
USU.NOME,
USU.CPF,
PC.PACOTE,
TP.TIPO,
CD.CATEGORIA,
USU.LAST_UPDATE,
CURRENT_TIMESTAMP
FROM DM_USUARIOS USU
LEFT JOIN DM_PACOTES PC ON PC.ID_PACOTE = USU.ID_PACOTE
LEFT JOIN DM_TIPOS_PACOTES TP ON TP.ID_PACOTE = PC.ID_PACOTE
LEFT JOIN DM_CATEGORIAS_DESTINO CD ON TP.ID_TIPO = CD.ID_TIPO
